# Generated by Django 4.0 on 2023-07-02 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stapp', '0002_alter_book_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('user', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=15, null=True)),
            ],
        ),
    ]
