# Generated by Django 4.0 on 2023-07-03 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stapp', '0005_alter_bookone_id_alter_booktwo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookone',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
