# Generated by Django 4.0 on 2023-07-03 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stapp', '0007_remove_book_picture_alter_bookone_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='picture',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='bookone',
            name='id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
